version: "3"

services:
  webpage-to-image-api:
    build: ./services/webpage-to-image-api
    environment:
      - PORT=3000
    volumes:
      - ./services/webpage-to-image-api/src:/app/src:delegated
    ports:
      - 5015:3000
    restart: always